### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by edudevvv** [zfcsoftware/funcaptcha-solver#1]
The extension is unable to resolve this type of captcha or when it gives an error it stops working.

![image](https://github.com/user-attachments/assets/0ee671a2-3a33-4c51-beb3-b000e53e3fc6)

**Comment by mdervisaygan** [comment]
Yes, there is a problem when that circle style captcha comes. Probably cap.guru api cannot solve it. 
https://cap.guru/en/profile/test-click/
Can you try selecting Funcaptcha > other from this link and enter the image you got from devtools and the text related to the image and try to resolve it? It probably won't resolve it. Since cap.guru is used as api, there is no change I can make. If you know a better visual recognition service, I can integrate it.

**Comment by mdervisaygan** [comment]
This problem is unfortunately related to cap.guru. Even if it restarts the test countless times, it will loop in vain because it cannot solve it. I suggest you improve your browser and ip quality.

Circle captcha result:
![image](https://github.com/user-attachments/assets/54a33bf1-c459-486b-90d6-6d393daa0b0b)

Normal captcha result:
![image](https://github.com/user-attachments/assets/3d9f86a7-a07d-475c-a42a-847eaaf579f6)

**Comment by mdervisaygan** [comment]
Since cap.guru support said that this captcha is difficult and cannot be solved, I am closing it. If you know a different image recognition api that can solve it, I can try it.
